# Generated by Django 6.0.6 on 2026-07-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='requires_quantity',
            field=models.BooleanField(default=False),
        ),
    ]
