# Generated by Django 6.0.6 on 2026-07-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_drink_requires_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='drink_image',
            field=models.ImageField(blank=True, null=True, upload_to='drink_images/'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu_item_image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
    ]
